# Generated by Django 6.0.3 on 2026-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C Language'), ('C++', 'C++'), ('Java', 'Java')], default='Python', max_length=50),
        ),
    ]
