# Generated by Django 6.0.3 on 2026-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_note_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Python', 'Python'), ('C', 'C Language'), ('Django', 'Django'), ('Java', 'Java')], default='Python', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='course_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C Language'), ('Django', 'Django'), ('Java', 'Java')], default='Python', max_length=50),
        ),
    ]
