# Generated by Django 6.0.3 on 2026-04-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_alter_note_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
